### All things that are shareable (without obvious ownership)

### Annotations / Directives
# deprecated stuff
directive @deprecated(reason: String = "No longer supported") on FIELD_DEFINITION | ENUM_VALUE

# authorization
enum RoleEnum {
	ADMIN
	USER
}
directive @auth(requires: RoleEnum = USER) on OBJECT | FIELD_DEFINITION

# Available date formatting
enum DateFormatEnum {
	RAW
	FULL
	SHORT
	RELATIVE
}

# Available price formatting
enum PriceFormatEnum {
	RAW
	FULL
	SHORT
	RELATIVE
}

### Interfaces
interface Entity {
	id: UuidV4!
}

# For Edges that have a timestamp,
# documenting the time of the connection
interface DatedEdge {
	createdAt: DateTime!
	# Can we guarantee all edges to have an `updatedAt` property
	# updatedAt: DateTime!
}

# Available sorting options
enum GenericSortBy {
	CREATED_AT
	UPDATED_AT
}

# Bare minium mutation response
enum ResponseCodeEnum {
	OK
	NOT_FOUND
	ERROR
	# TODO: Do we need more?
}
interface MutationResponse {
	code: ResponseCodeEnum!
	success: Boolean!
	data: Entity! # anything?
}

### Generic (re-usable) types
type Location {
	address: NonEmptyString
	zipCode: NonEmptyString
	city: NonEmptyString
	country: Country!
	lat: NonEmptyString
	long: NonEmptyString
}

# Available image sizes
enum ImageSizes {
	THUMB
	SMALL
	MEDIUM
	LARGE
}

type Image {
	# Absolute URL for accessing an image
	url(size: ImageSizes = SMALL): NonEmptyString!
	size: ImageSizes!
}
