global:
  scrape_interval: 5s
  evaluation_interval: 5s

# https://prometheus.io/docs/prometheus/latest/configuration/configuration/
scrape_configs:
  - job_name: api
    static_configs:
      - targets: ['api-graphql-svc:80']
